# Generated by Django 5.0.6 on 2024-06-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_invitation_invitee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='invitee',
        ),
    ]
