# Generated by Django 5.0.6 on 2024-06-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
